/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as FinancialLiteracyForEveryoneRouteImport } from './routes/financial-literacy-for-everyone'
import { Route as EsRouteImport } from './routes/es'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoneyBasicsIndexRouteImport } from './routes/money-basics.index'
import { Route as EsIndexRouteImport } from './routes/es.index'
import { Route as PathPathIdRouteImport } from './routes/path.$pathId'
import { Route as MoneyBasicsTopicRouteImport } from './routes/money-basics.$topic'
import { Route as EsOnboardingRouteImport } from './routes/es.onboarding'
import { Route as EsFinancialLiteracyForEveryoneRouteImport } from './routes/es.financial-literacy-for-everyone'
import { Route as EsDashboardRouteImport } from './routes/es.dashboard'
import { Route as EsCertificateRouteImport } from './routes/es.certificate'
import { Route as CompareKhanAcademyRouteImport } from './routes/compare.khan-academy'
import { Route as BlogWhatIsFinancialLiteracyRouteImport } from './routes/blog.what-is-financial-literacy'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as EsMoneyBasicsIndexRouteImport } from './routes/es.money-basics.index'
import { Route as LessonPathIdLessonIdRouteImport } from './routes/lesson.$pathId.$lessonId'
import { Route as EsCompareKhanAcademyRouteImport } from './routes/es.compare.khan-academy'
import { Route as EsBlogWhatIsFinancialLiteracyRouteImport } from './routes/es.blog.what-is-financial-literacy'
import { Route as ApiPublicHeroSfxRouteImport } from './routes/api/public/hero-sfx'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialLiteracyForEveryoneRoute =
  FinancialLiteracyForEveryoneRouteImport.update({
    id: '/financial-literacy-for-everyone',
    path: '/financial-literacy-for-everyone',
    getParentRoute: () => rootRouteImport,
  } as any)
const EsRoute = EsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyBasicsIndexRoute = MoneyBasicsIndexRouteImport.update({
  id: '/money-basics/',
  path: '/money-basics/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsIndexRoute = EsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EsRoute,
} as any)
const PathPathIdRoute = PathPathIdRouteImport.update({
  id: '/path/$pathId',
  path: '/path/$pathId',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyBasicsTopicRoute = MoneyBasicsTopicRouteImport.update({
  id: '/money-basics/$topic',
  path: '/money-basics/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const EsOnboardingRoute = EsOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => EsRoute,
} as any)
const EsFinancialLiteracyForEveryoneRoute =
  EsFinancialLiteracyForEveryoneRouteImport.update({
    id: '/financial-literacy-for-everyone',
    path: '/financial-literacy-for-everyone',
    getParentRoute: () => EsRoute,
  } as any)
const EsDashboardRoute = EsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EsRoute,
} as any)
const EsCertificateRoute = EsCertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => EsRoute,
} as any)
const CompareKhanAcademyRoute = CompareKhanAcademyRouteImport.update({
  id: '/compare/khan-academy',
  path: '/compare/khan-academy',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWhatIsFinancialLiteracyRoute =
  BlogWhatIsFinancialLiteracyRouteImport.update({
    id: '/blog/what-is-financial-literacy',
    path: '/blog/what-is-financial-literacy',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const EsMoneyBasicsIndexRoute = EsMoneyBasicsIndexRouteImport.update({
  id: '/money-basics/',
  path: '/money-basics/',
  getParentRoute: () => EsRoute,
} as any)
const LessonPathIdLessonIdRoute = LessonPathIdLessonIdRouteImport.update({
  id: '/lesson/$pathId/$lessonId',
  path: '/lesson/$pathId/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const EsCompareKhanAcademyRoute = EsCompareKhanAcademyRouteImport.update({
  id: '/compare/khan-academy',
  path: '/compare/khan-academy',
  getParentRoute: () => EsRoute,
} as any)
const EsBlogWhatIsFinancialLiteracyRoute =
  EsBlogWhatIsFinancialLiteracyRouteImport.update({
    id: '/blog/what-is-financial-literacy',
    path: '/blog/what-is-financial-literacy',
    getParentRoute: () => EsRoute,
  } as any)
const ApiPublicHeroSfxRoute = ApiPublicHeroSfxRouteImport.update({
  id: '/api/public/hero-sfx',
  path: '/api/public/hero-sfx',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/dashboard': typeof DashboardRoute
  '/es': typeof EsRouteWithChildren
  '/financial-literacy-for-everyone': typeof FinancialLiteracyForEveryoneRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/what-is-financial-literacy': typeof BlogWhatIsFinancialLiteracyRoute
  '/compare/khan-academy': typeof CompareKhanAcademyRoute
  '/es/certificate': typeof EsCertificateRoute
  '/es/dashboard': typeof EsDashboardRoute
  '/es/financial-literacy-for-everyone': typeof EsFinancialLiteracyForEveryoneRoute
  '/es/onboarding': typeof EsOnboardingRoute
  '/money-basics/$topic': typeof MoneyBasicsTopicRoute
  '/path/$pathId': typeof PathPathIdRoute
  '/es/': typeof EsIndexRoute
  '/money-basics/': typeof MoneyBasicsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/hero-sfx': typeof ApiPublicHeroSfxRoute
  '/es/blog/what-is-financial-literacy': typeof EsBlogWhatIsFinancialLiteracyRoute
  '/es/compare/khan-academy': typeof EsCompareKhanAcademyRoute
  '/lesson/$pathId/$lessonId': typeof LessonPathIdLessonIdRoute
  '/es/money-basics/': typeof EsMoneyBasicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/dashboard': typeof DashboardRoute
  '/financial-literacy-for-everyone': typeof FinancialLiteracyForEveryoneRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/what-is-financial-literacy': typeof BlogWhatIsFinancialLiteracyRoute
  '/compare/khan-academy': typeof CompareKhanAcademyRoute
  '/es/certificate': typeof EsCertificateRoute
  '/es/dashboard': typeof EsDashboardRoute
  '/es/financial-literacy-for-everyone': typeof EsFinancialLiteracyForEveryoneRoute
  '/es/onboarding': typeof EsOnboardingRoute
  '/money-basics/$topic': typeof MoneyBasicsTopicRoute
  '/path/$pathId': typeof PathPathIdRoute
  '/es': typeof EsIndexRoute
  '/money-basics': typeof MoneyBasicsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/hero-sfx': typeof ApiPublicHeroSfxRoute
  '/es/blog/what-is-financial-literacy': typeof EsBlogWhatIsFinancialLiteracyRoute
  '/es/compare/khan-academy': typeof EsCompareKhanAcademyRoute
  '/lesson/$pathId/$lessonId': typeof LessonPathIdLessonIdRoute
  '/es/money-basics': typeof EsMoneyBasicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/dashboard': typeof DashboardRoute
  '/es': typeof EsRouteWithChildren
  '/financial-literacy-for-everyone': typeof FinancialLiteracyForEveryoneRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/what-is-financial-literacy': typeof BlogWhatIsFinancialLiteracyRoute
  '/compare/khan-academy': typeof CompareKhanAcademyRoute
  '/es/certificate': typeof EsCertificateRoute
  '/es/dashboard': typeof EsDashboardRoute
  '/es/financial-literacy-for-everyone': typeof EsFinancialLiteracyForEveryoneRoute
  '/es/onboarding': typeof EsOnboardingRoute
  '/money-basics/$topic': typeof MoneyBasicsTopicRoute
  '/path/$pathId': typeof PathPathIdRoute
  '/es/': typeof EsIndexRoute
  '/money-basics/': typeof MoneyBasicsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/hero-sfx': typeof ApiPublicHeroSfxRoute
  '/es/blog/what-is-financial-literacy': typeof EsBlogWhatIsFinancialLiteracyRoute
  '/es/compare/khan-academy': typeof EsCompareKhanAcademyRoute
  '/lesson/$pathId/$lessonId': typeof LessonPathIdLessonIdRoute
  '/es/money-basics/': typeof EsMoneyBasicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certificate'
    | '/dashboard'
    | '/es'
    | '/financial-literacy-for-everyone'
    | '/mcp'
    | '/onboarding'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/what-is-financial-literacy'
    | '/compare/khan-academy'
    | '/es/certificate'
    | '/es/dashboard'
    | '/es/financial-literacy-for-everyone'
    | '/es/onboarding'
    | '/money-basics/$topic'
    | '/path/$pathId'
    | '/es/'
    | '/money-basics/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/hero-sfx'
    | '/es/blog/what-is-financial-literacy'
    | '/es/compare/khan-academy'
    | '/lesson/$pathId/$lessonId'
    | '/es/money-basics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificate'
    | '/dashboard'
    | '/financial-literacy-for-everyone'
    | '/mcp'
    | '/onboarding'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/what-is-financial-literacy'
    | '/compare/khan-academy'
    | '/es/certificate'
    | '/es/dashboard'
    | '/es/financial-literacy-for-everyone'
    | '/es/onboarding'
    | '/money-basics/$topic'
    | '/path/$pathId'
    | '/es'
    | '/money-basics'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/hero-sfx'
    | '/es/blog/what-is-financial-literacy'
    | '/es/compare/khan-academy'
    | '/lesson/$pathId/$lessonId'
    | '/es/money-basics'
  id:
    | '__root__'
    | '/'
    | '/certificate'
    | '/dashboard'
    | '/es'
    | '/financial-literacy-for-everyone'
    | '/mcp'
    | '/onboarding'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/what-is-financial-literacy'
    | '/compare/khan-academy'
    | '/es/certificate'
    | '/es/dashboard'
    | '/es/financial-literacy-for-everyone'
    | '/es/onboarding'
    | '/money-basics/$topic'
    | '/path/$pathId'
    | '/es/'
    | '/money-basics/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/hero-sfx'
    | '/es/blog/what-is-financial-literacy'
    | '/es/compare/khan-academy'
    | '/lesson/$pathId/$lessonId'
    | '/es/money-basics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificateRoute: typeof CertificateRoute
  DashboardRoute: typeof DashboardRoute
  EsRoute: typeof EsRouteWithChildren
  FinancialLiteracyForEveryoneRoute: typeof FinancialLiteracyForEveryoneRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BlogWhatIsFinancialLiteracyRoute: typeof BlogWhatIsFinancialLiteracyRoute
  CompareKhanAcademyRoute: typeof CompareKhanAcademyRoute
  MoneyBasicsTopicRoute: typeof MoneyBasicsTopicRoute
  PathPathIdRoute: typeof PathPathIdRoute
  MoneyBasicsIndexRoute: typeof MoneyBasicsIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHeroSfxRoute: typeof ApiPublicHeroSfxRoute
  LessonPathIdLessonIdRoute: typeof LessonPathIdLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-literacy-for-everyone': {
      id: '/financial-literacy-for-everyone'
      path: '/financial-literacy-for-everyone'
      fullPath: '/financial-literacy-for-everyone'
      preLoaderRoute: typeof FinancialLiteracyForEveryoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es': {
      id: '/es'
      path: '/es'
      fullPath: '/es'
      preLoaderRoute: typeof EsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money-basics/': {
      id: '/money-basics/'
      path: '/money-basics'
      fullPath: '/money-basics/'
      preLoaderRoute: typeof MoneyBasicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/': {
      id: '/es/'
      path: '/'
      fullPath: '/es/'
      preLoaderRoute: typeof EsIndexRouteImport
      parentRoute: typeof EsRoute
    }
    '/path/$pathId': {
      id: '/path/$pathId'
      path: '/path/$pathId'
      fullPath: '/path/$pathId'
      preLoaderRoute: typeof PathPathIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money-basics/$topic': {
      id: '/money-basics/$topic'
      path: '/money-basics/$topic'
      fullPath: '/money-basics/$topic'
      preLoaderRoute: typeof MoneyBasicsTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/onboarding': {
      id: '/es/onboarding'
      path: '/onboarding'
      fullPath: '/es/onboarding'
      preLoaderRoute: typeof EsOnboardingRouteImport
      parentRoute: typeof EsRoute
    }
    '/es/financial-literacy-for-everyone': {
      id: '/es/financial-literacy-for-everyone'
      path: '/financial-literacy-for-everyone'
      fullPath: '/es/financial-literacy-for-everyone'
      preLoaderRoute: typeof EsFinancialLiteracyForEveryoneRouteImport
      parentRoute: typeof EsRoute
    }
    '/es/dashboard': {
      id: '/es/dashboard'
      path: '/dashboard'
      fullPath: '/es/dashboard'
      preLoaderRoute: typeof EsDashboardRouteImport
      parentRoute: typeof EsRoute
    }
    '/es/certificate': {
      id: '/es/certificate'
      path: '/certificate'
      fullPath: '/es/certificate'
      preLoaderRoute: typeof EsCertificateRouteImport
      parentRoute: typeof EsRoute
    }
    '/compare/khan-academy': {
      id: '/compare/khan-academy'
      path: '/compare/khan-academy'
      fullPath: '/compare/khan-academy'
      preLoaderRoute: typeof CompareKhanAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/what-is-financial-literacy': {
      id: '/blog/what-is-financial-literacy'
      path: '/blog/what-is-financial-literacy'
      fullPath: '/blog/what-is-financial-literacy'
      preLoaderRoute: typeof BlogWhatIsFinancialLiteracyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/money-basics/': {
      id: '/es/money-basics/'
      path: '/money-basics'
      fullPath: '/es/money-basics/'
      preLoaderRoute: typeof EsMoneyBasicsIndexRouteImport
      parentRoute: typeof EsRoute
    }
    '/lesson/$pathId/$lessonId': {
      id: '/lesson/$pathId/$lessonId'
      path: '/lesson/$pathId/$lessonId'
      fullPath: '/lesson/$pathId/$lessonId'
      preLoaderRoute: typeof LessonPathIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/compare/khan-academy': {
      id: '/es/compare/khan-academy'
      path: '/compare/khan-academy'
      fullPath: '/es/compare/khan-academy'
      preLoaderRoute: typeof EsCompareKhanAcademyRouteImport
      parentRoute: typeof EsRoute
    }
    '/es/blog/what-is-financial-literacy': {
      id: '/es/blog/what-is-financial-literacy'
      path: '/blog/what-is-financial-literacy'
      fullPath: '/es/blog/what-is-financial-literacy'
      preLoaderRoute: typeof EsBlogWhatIsFinancialLiteracyRouteImport
      parentRoute: typeof EsRoute
    }
    '/api/public/hero-sfx': {
      id: '/api/public/hero-sfx'
      path: '/api/public/hero-sfx'
      fullPath: '/api/public/hero-sfx'
      preLoaderRoute: typeof ApiPublicHeroSfxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EsRouteChildren {
  EsCertificateRoute: typeof EsCertificateRoute
  EsDashboardRoute: typeof EsDashboardRoute
  EsFinancialLiteracyForEveryoneRoute: typeof EsFinancialLiteracyForEveryoneRoute
  EsOnboardingRoute: typeof EsOnboardingRoute
  EsIndexRoute: typeof EsIndexRoute
  EsBlogWhatIsFinancialLiteracyRoute: typeof EsBlogWhatIsFinancialLiteracyRoute
  EsCompareKhanAcademyRoute: typeof EsCompareKhanAcademyRoute
  EsMoneyBasicsIndexRoute: typeof EsMoneyBasicsIndexRoute
}

const EsRouteChildren: EsRouteChildren = {
  EsCertificateRoute: EsCertificateRoute,
  EsDashboardRoute: EsDashboardRoute,
  EsFinancialLiteracyForEveryoneRoute: EsFinancialLiteracyForEveryoneRoute,
  EsOnboardingRoute: EsOnboardingRoute,
  EsIndexRoute: EsIndexRoute,
  EsBlogWhatIsFinancialLiteracyRoute: EsBlogWhatIsFinancialLiteracyRoute,
  EsCompareKhanAcademyRoute: EsCompareKhanAcademyRoute,
  EsMoneyBasicsIndexRoute: EsMoneyBasicsIndexRoute,
}

const EsRouteWithChildren = EsRoute._addFileChildren(EsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificateRoute: CertificateRoute,
  DashboardRoute: DashboardRoute,
  EsRoute: EsRouteWithChildren,
  FinancialLiteracyForEveryoneRoute: FinancialLiteracyForEveryoneRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BlogWhatIsFinancialLiteracyRoute: BlogWhatIsFinancialLiteracyRoute,
  CompareKhanAcademyRoute: CompareKhanAcademyRoute,
  MoneyBasicsTopicRoute: MoneyBasicsTopicRoute,
  PathPathIdRoute: PathPathIdRoute,
  MoneyBasicsIndexRoute: MoneyBasicsIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHeroSfxRoute: ApiPublicHeroSfxRoute,
  LessonPathIdLessonIdRoute: LessonPathIdLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
