/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as FinancialLiteracyForEveryoneRouteImport } from './routes/financial-literacy-for-everyone'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoneyBasicsIndexRouteImport } from './routes/money-basics.index'
import { Route as PathPathIdRouteImport } from './routes/path.$pathId'
import { Route as MoneyBasicsTopicRouteImport } from './routes/money-basics.$topic'
import { Route as CompareKhanAcademyRouteImport } from './routes/compare.khan-academy'
import { Route as BlogWhatIsFinancialLiteracyRouteImport } from './routes/blog.what-is-financial-literacy'
import { Route as LessonPathIdLessonIdRouteImport } from './routes/lesson.$pathId.$lessonId'
import { Route as ApiPublicHeroSfxRouteImport } from './routes/api/public/hero-sfx'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialLiteracyForEveryoneRoute =
  FinancialLiteracyForEveryoneRouteImport.update({
    id: '/financial-literacy-for-everyone',
    path: '/financial-literacy-for-everyone',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyBasicsIndexRoute = MoneyBasicsIndexRouteImport.update({
  id: '/money-basics/',
  path: '/money-basics/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathPathIdRoute = PathPathIdRouteImport.update({
  id: '/path/$pathId',
  path: '/path/$pathId',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyBasicsTopicRoute = MoneyBasicsTopicRouteImport.update({
  id: '/money-basics/$topic',
  path: '/money-basics/$topic',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareKhanAcademyRoute = CompareKhanAcademyRouteImport.update({
  id: '/compare/khan-academy',
  path: '/compare/khan-academy',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWhatIsFinancialLiteracyRoute =
  BlogWhatIsFinancialLiteracyRouteImport.update({
    id: '/blog/what-is-financial-literacy',
    path: '/blog/what-is-financial-literacy',
    getParentRoute: () => rootRouteImport,
  } as any)
const LessonPathIdLessonIdRoute = LessonPathIdLessonIdRouteImport.update({
  id: '/lesson/$pathId/$lessonId',
  path: '/lesson/$pathId/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHeroSfxRoute = ApiPublicHeroSfxRouteImport.update({
  id: '/api/public/hero-sfx',
  path: '/api/public/hero-sfx',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/dashboard': typeof DashboardRoute
  '/financial-literacy-for-everyone': typeof FinancialLiteracyForEveryoneRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/what-is-financial-literacy': typeof BlogWhatIsFinancialLiteracyRoute
  '/compare/khan-academy': typeof CompareKhanAcademyRoute
  '/money-basics/$topic': typeof MoneyBasicsTopicRoute
  '/path/$pathId': typeof PathPathIdRoute
  '/money-basics/': typeof MoneyBasicsIndexRoute
  '/api/public/hero-sfx': typeof ApiPublicHeroSfxRoute
  '/lesson/$pathId/$lessonId': typeof LessonPathIdLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/dashboard': typeof DashboardRoute
  '/financial-literacy-for-everyone': typeof FinancialLiteracyForEveryoneRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/what-is-financial-literacy': typeof BlogWhatIsFinancialLiteracyRoute
  '/compare/khan-academy': typeof CompareKhanAcademyRoute
  '/money-basics/$topic': typeof MoneyBasicsTopicRoute
  '/path/$pathId': typeof PathPathIdRoute
  '/money-basics': typeof MoneyBasicsIndexRoute
  '/api/public/hero-sfx': typeof ApiPublicHeroSfxRoute
  '/lesson/$pathId/$lessonId': typeof LessonPathIdLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/dashboard': typeof DashboardRoute
  '/financial-literacy-for-everyone': typeof FinancialLiteracyForEveryoneRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/what-is-financial-literacy': typeof BlogWhatIsFinancialLiteracyRoute
  '/compare/khan-academy': typeof CompareKhanAcademyRoute
  '/money-basics/$topic': typeof MoneyBasicsTopicRoute
  '/path/$pathId': typeof PathPathIdRoute
  '/money-basics/': typeof MoneyBasicsIndexRoute
  '/api/public/hero-sfx': typeof ApiPublicHeroSfxRoute
  '/lesson/$pathId/$lessonId': typeof LessonPathIdLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certificate'
    | '/dashboard'
    | '/financial-literacy-for-everyone'
    | '/onboarding'
    | '/sitemap.xml'
    | '/blog/what-is-financial-literacy'
    | '/compare/khan-academy'
    | '/money-basics/$topic'
    | '/path/$pathId'
    | '/money-basics/'
    | '/api/public/hero-sfx'
    | '/lesson/$pathId/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificate'
    | '/dashboard'
    | '/financial-literacy-for-everyone'
    | '/onboarding'
    | '/sitemap.xml'
    | '/blog/what-is-financial-literacy'
    | '/compare/khan-academy'
    | '/money-basics/$topic'
    | '/path/$pathId'
    | '/money-basics'
    | '/api/public/hero-sfx'
    | '/lesson/$pathId/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/certificate'
    | '/dashboard'
    | '/financial-literacy-for-everyone'
    | '/onboarding'
    | '/sitemap.xml'
    | '/blog/what-is-financial-literacy'
    | '/compare/khan-academy'
    | '/money-basics/$topic'
    | '/path/$pathId'
    | '/money-basics/'
    | '/api/public/hero-sfx'
    | '/lesson/$pathId/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificateRoute: typeof CertificateRoute
  DashboardRoute: typeof DashboardRoute
  FinancialLiteracyForEveryoneRoute: typeof FinancialLiteracyForEveryoneRoute
  OnboardingRoute: typeof OnboardingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogWhatIsFinancialLiteracyRoute: typeof BlogWhatIsFinancialLiteracyRoute
  CompareKhanAcademyRoute: typeof CompareKhanAcademyRoute
  MoneyBasicsTopicRoute: typeof MoneyBasicsTopicRoute
  PathPathIdRoute: typeof PathPathIdRoute
  MoneyBasicsIndexRoute: typeof MoneyBasicsIndexRoute
  ApiPublicHeroSfxRoute: typeof ApiPublicHeroSfxRoute
  LessonPathIdLessonIdRoute: typeof LessonPathIdLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-literacy-for-everyone': {
      id: '/financial-literacy-for-everyone'
      path: '/financial-literacy-for-everyone'
      fullPath: '/financial-literacy-for-everyone'
      preLoaderRoute: typeof FinancialLiteracyForEveryoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money-basics/': {
      id: '/money-basics/'
      path: '/money-basics'
      fullPath: '/money-basics/'
      preLoaderRoute: typeof MoneyBasicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path/$pathId': {
      id: '/path/$pathId'
      path: '/path/$pathId'
      fullPath: '/path/$pathId'
      preLoaderRoute: typeof PathPathIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money-basics/$topic': {
      id: '/money-basics/$topic'
      path: '/money-basics/$topic'
      fullPath: '/money-basics/$topic'
      preLoaderRoute: typeof MoneyBasicsTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/khan-academy': {
      id: '/compare/khan-academy'
      path: '/compare/khan-academy'
      fullPath: '/compare/khan-academy'
      preLoaderRoute: typeof CompareKhanAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/what-is-financial-literacy': {
      id: '/blog/what-is-financial-literacy'
      path: '/blog/what-is-financial-literacy'
      fullPath: '/blog/what-is-financial-literacy'
      preLoaderRoute: typeof BlogWhatIsFinancialLiteracyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$pathId/$lessonId': {
      id: '/lesson/$pathId/$lessonId'
      path: '/lesson/$pathId/$lessonId'
      fullPath: '/lesson/$pathId/$lessonId'
      preLoaderRoute: typeof LessonPathIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hero-sfx': {
      id: '/api/public/hero-sfx'
      path: '/api/public/hero-sfx'
      fullPath: '/api/public/hero-sfx'
      preLoaderRoute: typeof ApiPublicHeroSfxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificateRoute: CertificateRoute,
  DashboardRoute: DashboardRoute,
  FinancialLiteracyForEveryoneRoute: FinancialLiteracyForEveryoneRoute,
  OnboardingRoute: OnboardingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogWhatIsFinancialLiteracyRoute: BlogWhatIsFinancialLiteracyRoute,
  CompareKhanAcademyRoute: CompareKhanAcademyRoute,
  MoneyBasicsTopicRoute: MoneyBasicsTopicRoute,
  PathPathIdRoute: PathPathIdRoute,
  MoneyBasicsIndexRoute: MoneyBasicsIndexRoute,
  ApiPublicHeroSfxRoute: ApiPublicHeroSfxRoute,
  LessonPathIdLessonIdRoute: LessonPathIdLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
